part of flashcards;

class Data {
  
  static List<String> getSeedData() {
    
    return [        
//Letters
"alef|ﺍ|alef|letter",
"be|ب|be|letter",
"pe|پ|pe|letter",
"te|ﺕ|te|letter",
"se|ﺙ|se|letter",
"jim|ﺝ|jim|letter",
"che|ﭺ|che|letter",
"he|ﺡ|he|letter",
"khe|ﺥ|khe|letter",
"daal|ﺩ|daal|letter",
"zaal|ﺫ|zaal|letter",
"re|ﺭ|re|letter",
"ze|ﺯ|ze|letter",
"zhe|ژ|zhe|letter",
"sin|ﺱ|sin|letter",
"shin|ﺵ|shin|letter",
"saad|ﺹ|saad|letter",
"zaad|ﺽ|zaad|letter",
"ta|ﻁ|ta|letter",
"za|ﻅ|za|letter",
"ein|ﻉ|ein|letter",
"ghein|ﻍ|ghein|letter",
"fe|ﻑ|fe|letter",
"qaaf|ﻕ|qaaf|letter",
"kaaf|ک|kaaf|letter",
"gaaf|گ|gaaf|letter",
"laam|ﻝ|laam|letter",
"mim|ﻡ|mim|letter",
"noon|ﻥ|noon|letter",
"vav|و|vav|letter",
"he|ﻩ|he|letter",
"ye|ﻯ|ye|letter",

//Digit
"0|۰|sefr|digit",
"1|۱|yek|digit",
"2|۲|do|digit",
"3|۳|seh|digit",
"4|۴|char|digit",
"5|۵|panj|digit",
"6|۶|sheesh|digit",
"7|۷|haft|digit",
"8|۸|hasht|digit",
"9|۹|noh|digit",
"ten|ده|dah|digit",
"eleven|یازده|yazdah|digit,number",
"twelve|دوازده|davaazdah|digit,number",
"thirteen|سیزده|sizdah|digit,number",
"fourteen|چهارده|chardah|digit,number",
"fifteen|پانزده|panzdah|digit,number",
"sixteen|شانزده|shanzdah|digit,number",
"seventeen|هفده|hefdah|digit,number",
"eighteen|هجده|hejdah|digit,number",
"nineteen|نوزده|noozdah|digit,number",
"twenty|بیست|bist|digit,number",
"twenty one|بیست و یک|bist o yek|digit,number",
//"thirty|||digit,number",
//"thirty one|||digit,number",
//"forty|||digit,number",
//"fifty|||digit,number",
//"sixty|||digit,number",
//"seventy|||digit,number",
//"eighty|||digit,number",
//"ninety|||digit,number",
//"one hundred|||digit,number",



//Food
"water|آب|ab|noun,food,drink",
"juice|آبمیوه|abmiveh|noun,food,drink",
"beer|آبجو|abjo|noun,food,drink",
"wine|شراب|sharab|noun,food,drink",
"milk|شیر|sib|noun,food,drink",
"tea|چای|chai|",

"chicken|جوجه|joojeh|noun,food,animal",
"beef|گوشت گاو|goosht e gav|noun,food",
"lamb|بره|barreh|noun,food",

//Fruit
"apple|سیب|sib|noun,food,fruit",
"apricot|زردآلو|zardaaloo|noun,food,fruit",
"banana|موز|moz|noun,food,fruit",
"barberry|زرشک|zereshk|noun,food,fruit",
"berry|توت|toot|noun,food,fruit",
"mulberry / blackberry|شاه توت|shaahtoot|noun,food,fruit",
"cherry|گیلاس|gilaas|noun,food,fruit",
"grape|انگور|angoor|noun,food,fruit",
"lemon, lime|لیمو|limoo|noun,food,fruit",
"mango|انبه|anbeh|noun,food,fruit",
"melon|خربزه|kharbozeh|noun,food,fruit",
"nectarine|شلیل|shalil|noun,food,fruit",
"orange|پرتقال|porteghaal|noun,food,fruit",
"peach|هلو|holoo|noun,food,fruit",
"pear|گلابی|golaabi|noun,food,fruit",
"pineapple|آناناس|aanaanaas|noun,food,fruit",
"plum|آلو|aaloo|noun,food,fruit",
"pomegranate|انار|anaar|noun,food,fruit",
"raspberry|تمشک|tameshk|noun,food,fruit",
"strawberry|توت فرنگی|toot farangi|noun,food,fruit",
"tangerine|نارنگی|naarangi|noun,food,fruit",
"watermelon|هندوانه|hendavaaneh|noun,food,fruit",
"fig|انجیر|anjir|noun,food,fruit",
"date|خرما|khormaa|noun,food,fruit",
"coconut|نارگیل|naargil|noun,food,fruit",


//Vegetables
"asparagus|مارچوبه|maarchoobeh|noun,food,vegetable",
"beet|چغندر|choghondar|noun,food,vegetable",
"bell pepper|فلفل دلمه ای|felfel dolmei|noun,food,vegetable",
"broccoli|کلم بروکلی|kalam brokli|noun,food,vegetable",
"cabbage|کلم|kalam|noun,food,vegetable",
"carrot|هویج|havij|noun,food,vegetable",
"cauliflower|گل کلم|golkalam|noun,food,vegetable",
"celery|کرفس|karafs|noun,food,vegetable",
"corn|ذرّت|zorrat|noun,food,vegetable",
"cucumber|خیار|khiyaar|noun,food,vegetable",
"eggplant|بادمجان|baademjoon|noun,food,vegetable",
"green bean|لوبیا سبز|loobiyaasabz|noun,food,vegetable",
"green onion|پیازچه|piyaazche|noun,food,vegetable",
"lettuce|کاهو|kaahoo|noun,food,vegetable",
"mushroom|قارچ|ghaarch|noun,food,vegetable",
"onion|پیاز|piyaaz|noun,food,vegetable",
"peas|نخود فرنگی|nokhod farangi|noun,food,vegetable",
"pepper|فلفل|felfel|noun,food,vegetable",
"potato|سیب زمینی|sibzamini|noun,food,vegetable",
"pumpkin|کدو تنبل|kadoo tanbal|noun,food,vegetable",
"radish|تربچه|torobche|noun,food,vegetable",
"spinach|اسفناج|esfenaaj|noun,food,vegetable",
"tomato|گوجه فرنگی|gojefarangi|noun,food,vegetable",
"turnip|شلغم|shalgham|noun,food,vegetable",
"yam|سیب زمینی شیرین|sibzamini shirin|noun,food,vegetable",
"zucchini, squash|کدو|kadoo|noun,food,vegetable",

//Herbs and Spices
"basil|ریحان|reyhoon|noun,food,herb",
"cinnamon|دارچین|daarchin|noun,food,herb",
"cloves|میخک|mikhak|noun,food,herb",
"coriander|گشنیز|geshniz|noun,food,herb",
"cumin|زیره|zireh|noun,food,herb",
"dill|شوید|shevid|noun,food,herb",
"fennel|رازیانه|raaziaaneh|noun,food,herb",
"fenugreek|شنبلیله|shanbalileh|noun,food,herb",
"garlic|سیر|sir|noun,food,herb,vegetable",
"ginger|زنجبیل|zanjebil|noun,food,herb,vegetable",
"mint|نعناع|nanaa|noun,food,herb",
"nutmeg|جوز هندی|joz e hendi|noun,food,herb",
"oregano|پونه کوهی|pooneh koohi|noun,food,herb",
"parsley|جعفری|jafari|noun,food,herb",
"poppy|خشخاش|khashkhaash|noun,food,herb",
"rosemary|رزماری|rozmaary|noun,food,herb",
"saffron|زعفران|zafaroon|noun,food,herb",
"salt|نمک|namak|noun,food,herb",
"sesame|کنجد|konjed|noun,food,herb",
"tarragon|ترخان|tarkhoon|noun,food,herb",
"thyme|آویشن|aavishan|noun,food,herb",
"turmeric|زردچوبه|zard choobeh|noun,food,herb",
"vanilla|وانیل|vaanil|noun,food,herb",

"rice|برنج|berenj|noun,food",
"bread|نان|noon|noun,food",
"lentil|عدس|adas|noun,food",
"bean|لوبیا|loobiyaa|noun,food",
"chickpea|نخود|nokhod|noun,food",
"flour|ارد|aard|noun,food",
"wheat|گندم|gandom|noun,food",
"pasta|پاستا|paastaa|noun,food",
"sugar|شکر|shekar|noun,food",

"cheese|پنیر|panir|noun,food,processed",
"butter|کره|kareh|noun,food,processed",
"yoghurt|ماست|maast|noun,food,processed",
"cream|خامه|khameh|noun,food,processed",
"ice cream|بستنی|bastani|noun,food,processed",

"olive|زیتون|zeitoon|noun,food,processed",
"pickle|ترشی|torshi|noun,food,processed",
"almond|بادام|baadom|noun,food,processed,nut",
"walnut|گردو|gerdoo|noun,food,processed,nut",
"peanut|بادام زمینی|baadom zamini|noun,food,processed,nut",
"pistachio|پسته|pesteh|noun,food,processed,nut",
"hazelnut|فندق|fandogh|noun,food,processed,nut",
"mayonnaise|مایونز|maayonez|noun,food,processed",
"mustard|خردل|khardal|noun,food,processed",
"ketchup|کچاپ|kechaap|noun,food,processed",
"vinegar|سرکه|serkeh|noun,food,processed",
"oil|روغن|rooghan|noun,food,processed",
"soy sauce|سس سویا|ses soyaa|noun,food,processed",
"lemon juice|ابلیمو|aablimu|noun,food,processed",
"honey|عسل|asal|noun,food,processed",

//Animal
"bear|خرس|khers|noun,animal",
"tiger|ببر|babr|noun,animal",
"goat|بز|boz|noun,animal",
"sheep|گوسفند|goosfand|noun,animal",
"duck|اردک|ordak|noun,animal",
"cow|گاو|gav|noun,animal",
"fish|ماهی|mahi|noun,animal",

//Time
"Monday|دوشنبه|doshanbeh|noun,time",
"Tuesday|سه شنبه|seshanbeh|noun,time",
"Wednesday|چهارشنبه|charshanbeh|noun,time",
"Thursday|پنج شنبه|panjshanbeh|noun,time",
"Friday|جمعه|jome|noun,time",
"Saturday|شنبه|shanbeh|noun,time",
"Sunday|یکشنبه|yekshanbeh|noun,time",
"yesterday|ديروز|dirooz|noun,time",
"today|امروز|emrooz|noun,time",
"tomorrow|فردا|fardaa|noun,time",
"day|روز|rooz|noun,time",
"night|شب|shab|noun,time",
"week|هفته|hafteh|noun,time",
"month|ماه|maah|noun,time",
"year|سال|saal|noun,time",
"second|ثانيه|saaniyeh|noun,time",
"minute|دقيقه|daghigheh|noun,time",
"hour|ساعت|saa'at|noun,time",
"morning|صبح|sobh|noun,time",
"evening|عصر|asr|noun,time",
"noon|ظهر|zohr|noun,time",
"afternoon|بعد از ظهر|ba'ad az zohr|noun,time",
"midnight|نصفه شب|nesfeh shab|noun,time",
"now|حالا|haalaa|noun,time",
"later|بعداً|badan|noun,time",

//Body Parts
//"face|||",
//"head|||",
//"eye|||",
//"mouth|||",
//"nose|||",
//"ear|||",
//"hair|||",
//"finger|||",
//"hand|||",
//"arm|||",
//"leg|||",
//"foot|||",
//"toe|||",
//"shoulder|||",
//"stomach|||",
//"elbow|||",
//"knee|||",

//Kitchen Items
//"knife|||noun,kitchen",
//"fork|||noun,kitchen",
//"spoon|||noun,kitchen",
"plate|بشقاب|boshghaab|noun,kitchen",
"bowl|کاسه|kaaseh|noun,kitchen",
"cup|فنجان|fenjoon|noun,kitchen",
//"glass|||noun,kitchen",
//"pot|||noun,kitchen",
//"frying pan|||noun,kitchen",
//"spatula|||noun,kitchen",
//"scissors|||noun,kitchen",
//"tape|||noun,kitchen",
//"glue|||noun,kitchen",
//"|||noun,kitchen",

//School
"book|کتاب|ketaab|noun,school",
"newspaper|روزنامه|rooznaameh|noun,school",
"letter|نامه|naameh|noun,school",
"magazine|مجله|majaleh|noun,school",
//"pen||khodkar|noun,school",
//"pencil||medaad|noun,school",
//"paper|||noun,school",




//People
"man|مرد|mard|noun,people",
"woman|زن|zen|noun,people",
"boy|پسر|pisar|noun,people",
"girl|دختر|dokhtar|noun,people",
"child|کودک|bacheh|noun,people",
"police|پلیس|polis|noun,people",
"teacher|معلم|mo'alem|noun,people",
"doctor|دکتر|doktor|noun,people",
" school student|دانش آموز|daanesh aamooz|",
"university student|دانشجو|daaneshjoo|",


//Places
//"home|||noun, places",
//"work|||noun, places",
//"school|||noun, places",
//"|||noun, places",
//transportation
//"airplane|||noun, transportation",
//"boat|||noun, transportation",
"bicycle|دوچرخه |docharkheh|noun, transportation",
//"car||maachin|noun, transportation",
//"train|||noun, transportation",
//"bus|||noun, transportation",

//Furniture
"table|میز|miz|noun, furniture",
//"chair|||noun, furniture",
//"oven|||noun, furniture",
//"refrigerator|||noun, furniture",
//"television|||noun, furniture",
//"couch|||noun, furniture",
//"carpet|||noun, furniture",
//"window|||noun, furniture",
//"balcony|||noun, furniture",
//"bed|||noun, furniture",
//"desk|||noun, furniture",
//"lamp|||noun, furniture",
//"microwave|||noun, furniture",
//"toaster|||noun, furniture",
//"kettle|||noun, furniture",

//Clothing
"dress shirt / dress|پیراهن|piraahan|noun, clothing",
"tshirt|تی شرت|tishert|",
"pants|شلوار|shalvaar|noun, clothing",
//"underwear|||noun, clothing",
//"sock|||noun, clothing",
"shoe|کفش|kafsh|noun, clothing",
//"boot|||noun, clothing",
"overcoat|پالتو |paalto|noun, clothing",
//"coat|||noun, clothing",
"skirt|دامن|daaman|noun, clothing",
//"hat|||noun, clothing",
//"belt|||noun, clothing",
//"glasses|||noun, clothing",

//nature
"flower|گل|gol|noun,nature",
"moon|ماه|maah|noun,nature",
"sun|خورشید|khorshid|noun,nature",
"grass|چمن|chaman|noun,nature",
"sky|آسمان|aasemaan|noun,nature",
"tree|درخت|derakht|noun,nature",

"this|این|in|pronoun",
"these|اینها|inhaa|pronoun",
"that|ان|aan|pronoun",
"those|آنها|aanhaa|pronoun",
"here|اینجا|injaa|pronoun",
"there|آنجا|aanjaa|pronoun",
"I|من|man|pronoun",
"you (singular)|تو|to|pronoun",
"he/she|او|Oo|pronoun",
"we|ما|maa|pronoun",
"you (plural)|شما|shomaa|pronoun",
"they|آنها|aanhaa|pronoun",

//Prepositions
"after|بعداز|ba'daaz|preposition",
"before|قبل از|ghablaz|preposition",
//"about|||preposition",
"in|دَر|dar|preposition",
//"into|||preposition",
//"like|||preposition",
"of/from|از|az|preposition",
"on|روی|rooyeh|preposition",
//"out|||preposition",
"over/above|بَر|bar|preposition",
//"through|||preposition",
"to|به|beh|preposition",
"under|زیر|zir|preposition",
"with|با|baa|preposition",
"without|بدون / بی|bedoon / bi|preposition",

//Conjunctions
"and|و|va|conjunction",
"or|یا|yaa|conjunction",
"yes|بله|baleh|conjunction",
"no|نه|nah|conjunction",

//Verbs
//"to be (present)||hast-|verb",
//"to be (past)||bood-|verb",
//"to have (present)||dar-|verb",
//"to have (past)||dasht-|verb",
//"to want (present)||mikhah-|verb",
//"to want (past)||khast-|verb",
//"to buy (present)||mikhar-|verb",
//"to buy (past)||kharid-|verb",
//"to do (present)||mikon-|verb",
//"to do (past)||kard-|verb",
//"to say||migooy-|verb",
//"to say (past)||goft-|verb",
//"to get|||verb",
//"to see|||verb",
//"to cook||daar- aashpazi mikon-|verb",
//"||paz|verb",
//"to cook (past)||pokhtan|verb",
//"to eat|| daar- mikhor-|verb",
//"to eat (past)||khordan|verb",
//"to swim (present)||daar- shenaa mikon-|verb",
//"to read||daar- mikhaan-|verb",
//"to read (past)||khaandan|verb",
//"to write||daar- minevis|verb",
//"to run|| daar- midav-|verb",
//"to walk|||verb",
//"to drive||daar- raanandegi mikon-|verb",
//"to sleep (present)||khaab|verb",
//"to sleep (past)||khaabidan|verb",
//"to go||mirev-|verb",

"what|چی|Chi|question",
"what (work)|چه کار|chikar|question",
"how many|چند|chand|question",
"how much|چقدر|cheghadr|question",
"what is|چیست|chist|question",
"where|کجا|Koja|question",
"why|چرا|Chara|question",
"who|کی|Ki|question",
"when|کی|kei|question",



//Colour
"black|سیاه|seeyah|adjective,colour",
"blue|آبی|abi|adjective,colour",
"brown|قهوه ای|ghah-ve-yee|adjective,colour",
"grey|خاکستری|khakestari|adjective,colour",
"green|سبز|sabz|adjective,colour",
"orange|نارنجی|naarenji|adjective,colour",
"purple|بنفش|banafsh|adjective,colour",
"red|قرمز|ghermez|adjective,colour",
"white|سفيد|sefeed|adjective,colour",
"yellow|زرد|zard|adjective,colour",
"pink|صورتی|soorati|adjective,colour",

//Size
"big|بزرگ|bozorg|adjective,size",
"small|کوچک|koochek|adjective,size",
"deep|گود|god|adjective,size",
"shallow|کم عمق|kam omgh|adjective,size",
"long|دراز|deraaz|adjective,size",
"short|کوتاه|kootaah|adjective,size",
"wide|پهن|pahn|adjective,size",
"narrow|باريک|baarik|adjective,size",
"thick|کلفت|koloft|adjective,size",
"thin|نازک|naazok|adjective,size",
//"loose|||",

//Taste
"bitter|تلخ|talkh|adjective,taste",
"fresh|تازه|taazeh|adjective,taste",
"salty|شور|shoor|adjective,taste",
"sour|ترش|torsh|adjective,taste",
"sweet|شيرين|shirin|adjective,taste",
"spicy|تند|tond|adjective,taste",

//Qualities
"good|خوب|khoob|adjective,quality",
"bad|بد|bad|adjective,quality",
"clean|تميز|tamiz|adjective,quality",
"dirty|کثيف|kasif|adjective,quality",
"light (illumination)|چراغ|cheraagh|adjective,quality",
"dark|تاریک|taarik|adjective,quality",
"easy|آسان|aasoon|adjective,quality",
"difficult|سخت|sakht|adjective,quality",
"dry|خشک|Khoshk|adjective,quality",
"wet|خیس|khis|adjective,quality",
"full|پر|por|adjective,quality",
"empty|خالی|khaali|adjective,quality",
"cheap|ارزان|arzoon|adjective,quality",
"expensive|گران|geroon|adjective,quality",
"fast|سريع|sari|adjective,quality",
"slow|آهسته|aahesteh|adjective,quality",
"foreign|خارجی|khaariji|adjective,quality",
"local|محلی|mahalli|adjective,quality",
"hard (firm)|سفت|seft|adjective,quality",
"soft|نرم|narm|adjective,quality",
"heavy|سنگين|sangin|adjective,quality",
"light (weight)|سبک|sabok|adjective,quality",
"new|جدید|jadid|adjective,quality",
"old (thing)|کهنه|kohneh|adjective,quality",
"young (person)|جوان|javoon|adjective,quality",
"old (person)|پير|peer|adjective,quality",
"noisy (person)|پرحرف|porharf|adjective,quality",
"quiet (person)|بی سروصدا|bi saro sedaa|adjective,quality",
"noisy (sound)|بلند|boland|adjective,quality",
"quiet (sound)|آرام|aaroom|adjective,quality",
"powerful|قوی|qavi|adjective,quality",
"weak|ضعيف|zaeef|adjective,quality",
"correct|درست|dorost|adjective,quality",
"wrong|غلط|ghalat|adjective,quality",
//"smart|| bahoosh|adjective,quality",
//"stupid|||",
"asleep|خوابیده|khaabideh|adjective,quality",
//"awake|||",

//Quantities
"few|کم|kam|adjective,quantity",
"many|زياد|zeeyaad|adjective,quality",
//some 
//Some
"very|خيلی|kheili|adjective,quality",
"part|قسمت|qesmat|adjective,quality",
"whole|همه|hamey|adjective,quality",

//Phrase
"Hi|سلام|salam|phrase",
"Good morning|صبح بخیر|Sobh Be kheyr|phrase",
"Good evening|عصر بخیر|Asr be kheyr|phrase",
"Good night|شب بخیر|Shab be kheyr|phrase",
"Welcome|خوش آمدید|Khosh Amadid|phrase",
"How are you?|حال شما چطور هست|Haleh shoma chetor hast?|phrase",
"Thank you|ممنون|Mamnoon|phrase",
"You're welcome|خواهش میکنم|Khahesh mikonam|phrase",
"See you later|بعدأ میبینمت|Ba’adan mibinamet|phrase",
"Nice to meet you|از ملاقات شما خوش وقتم|Az molaghat e sham khosh vaghtam|phrase",
"Good luck|موفق باشید|Mo’afagh bashed|phrase",
"Congratulations|تبریک می گویم|Tabrik migoyam|phrase",
"Sorry|ببخشید|Bebakhshid|phrase",
"No Problem|مشکلی نیست|Moshkeli nist|phrase",
"I need to practice my Persian|من باید فارسی رو بیشتر تمرین کنم|Man bayad farsi ro bishtar tamrin konam|phrase",
"I love you|دوست دارم|Dooset daram|phrase"

  
    ];
  }
}